name: flutter_native_localizations
description: "Flutter localization that doesn't bloat your app. Native strings, zero overhead."
version: 0.0.1
homepage: https://github.com/patricktailor/flutter_native_localizations

environment:
  sdk: ^3.8.1
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  jni: ^0.14.2
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  jnigen: ^0.14.2
  very_good_analysis: ^9.0.0

flutter:
  plugin:
    platforms:
      android:
        ffiPlugin: true